app/main/views/briefs.py, tests/app/main/test_briefs.py
We are adding a new
- 'awarded' status for briefs
- 'pending-awarded' and 'awarded' status for brief responses.
I have crawled through this repository looking for knock on effects when we shortly add a new 
'award' status for briefs. I only found one location that we needed to change to ensure existing behaviour.
Note, I also found places using the helper method `supplier_has_a_brief_response`:
```
def supplier_has_a_brief_response(data_api_client, supplier_id, brief_id):
brief_responses = data_api_client.find_brief_responses(brief_id=brief_id, supplier_id=supplier_id)['briefResponses']
return len(brief_responses) != 0
```
This would need changes to ensure the original intended behaviour to request brief responses remains i.e. that we request 'submitted', 'pending-awarded', and 'awarded' …
=> Ensure existing functionality for users when adding a new brief and brief response statuses

app/external/views/external.py, app/main/__init__.py, app/main/views/frameworks.py, app/templates/briefs/view_response_result.html, app/templates/frameworks/opportunities_dashboard.html, tests/app/main/test_briefs.py, tests/app/main/test_frameworks.py
MUST BE MERGED BEFORE [https://github.com/alphagov/digitalmarketplace-supplier-frontend/pull/731](https://github.com/alphagov/digitalmarketplace-supplier-frontend/pull/731)
The opportunites dashboard for a supplier shows them their responses to
opportunities. It makes sense to move it to the brief responses frontend
app.
The url is slightly different to where it was before, so a 301 redirect
will be put in place in the supplier app to point to this new url.
This means we can also get rid of one of the external links.
=> Import opportunities dashboard

app/main/views/briefs.py, tests/app/main/test_briefs.py
Fourth of 5 backwards compatibility PRs to handle the two new Brief statuses, `cancelled` and `unsuccessful`.
1. Admin FE alphagov/digitalmarketplace-admin-frontend#293
2. Buyer FE https://github.com/alphagov/digitalmarketplace-buyer-frontend/pull/588
3. Scripts alphagov/digitalmarketplace-scripts#144
4. Brief Responses FE 
5. Briefs FE https://github.com/alphagov/digitalmarketplace-briefs-frontend/pull/17
See #2 for the equivalent changes for the awarded status.
- Adds new cancelled and unsuccessful statuses to existing Brief status lists
- Update tests and test fixtures
- Also increased the strictness of some existing tests that checked for an invalid status only.
=> Backwards compatibility for new Brief statuses

app/external/views/external.py, app/main/views/briefs.py, app/templates/briefs/view_response_result.html, app/templates/frameworks/opportunities_dashboard.html, tests/app/helpers.py, tests/app/main/test_briefs.py, tests/app/main/test_frameworks.py
https://trello.com/c/T6AICSmb/711-2-update-supplier-response-page-and-dashboard-based-on-brief-status
Reviewers: My commits are pretty tidy, you may find it easier to review commit by commit
- show application status on dashboard
- don't show 'what to do next' content on view your brief response page if the outcome of the brief is known
- add link to view the opportunity (and outcome)
- no longer show persistent flash messages on the view your response page
- Change breadcrumbs on the view your response page to point back to the applications overview page rather than the list of DOS opportunities
An example of when the outcome of the brief is known
An example of when the outcome of the brief is not known
An example of when one of our legacy briefs which has an unsuccessful application …
=> Show application status on application dashboard

app/main/helpers/__init__.py, app/main/views/briefs.py, config.py, tests/app/main/test_briefs.py
The code removed was not tidyed up after the new supplier flow for
applying to a brief was released and given two weeks to allow all
'old style' or 'legacy' briefs to finish their `live` period.
Now we have no more 'old style' briefs that are live, we do not
need to do these additional checks as they will never be false.
=> Remove code related to migration period of new supplier flow

.flake8, config.py, requirements-dev.txt
Add flake8 per-file-ignores, in place of flake8-putty, so that we can support newer Python3 syntax like eg f-strings and type annotations.
Flake8 report:
```
/Users/samuelwilliams/git/digitalmarketplace-brief-responses-frontend/venv/bin/flake8 .
./config.py:106:1: E305 expected 2 blank lines after class or function definition, found 1
./app/__init__.py:0:1: X100 Superfluous per-file-ignores for E402
make: *** [test-flake8] Error 1
```
=> Change from flake8-putty to per-file-ignores

app/templates/briefs/check_your_answers.html, tests/app/main/test_briefs.py
Since we changed the application journey we have had several suppliers who failed to submit an application in time because they did not realise that their application had not been submitted at the point of reaching the check your answers page.
After reviewing what the suppliers told us we believe that they are looking at the content on the page but they just did not realise they still needed to perform an action.
We are proposing this small content change which has been signed off by Jane and will monitor wether we continue to receive support queries.
Before:
After:
=> Change heading copy for brief responses application

app/main/views/briefs.py, tests/app/main/test_briefs.py
https://trello.com/c/fpNVMkMj/344-500-on-brief-responses-fe-at-suppliers-opportunities-brief
The external URL for the public brief page (`/digital-outcomes-and-specialists/opportunities/<brief_id>`) is managed within the Buyer FE.
There is an edge case where a supplier may try to manipulate the URL from their
brief application flow to reach the public brief page, which never reaches the Buyer FE because of the `/suppliers/opportunities/...` prefix, which nginx routes to the Brief Responses FE (here!).
It seems likely that the supplier is trying to reach the public brief page (there's no link for this on the result page following a successful brief response application, for example). 
The redirect replaces the 'suppliers' part of the prefix with the correct framework name, which allows …
=> Redirect malformed URL to public brief page

app/main/helpers/briefs.py
Because we now have 3 different methods of sending emails we should update utils to ensure `send_email` is imported from the client specific sub-directory of `emails` in utils
=> Update import to import send_email from dm_mandrill

app/templates/briefs/_brief_response_data.html, tests/app/main/test_briefs.py
Trello: https://trello.com/c/sYJYKnK9/58-how-summary-tables-handle-their-links-means-pages-can-contain-multiple-links-with-duplicate-text
The Check Your Answers summary page contains several Edit links. Screen reader users may find it difficult to distinguish between them:
The `summary_table.top_link` macro in the frontend toolkit now has an additional `hidden_text` field  (as we currently do for the `edit_link` macro) which is rendered in a `<span class="visually-hidden"></span>` inside the link. 
We don't use the macro for edit links within a summary table, so the spans are hardcoded there. 
~~This can be merged once the FE toolkit PR is ready to pull in (Travis will fail on the yarn install step at the moment): https://github.com/alphagov/digitalmarketplace-frontend-toolkit/pull/406~~ …
=> Accessibility fixes for summary table Edit links

app/status/views.py, requirements-app.txt, requirements.txt
The status endpoint for all of the apps is highly redundant across
repositories so I've moved it to dm-utils. We now only need to call this
method from the view stub in each app and pass in a couple of resources
(mainly the current_app and any api clients) to get a consistent status
JSON blob back.
https://trello.com/c/BBvu6eUk/383-ensure-healthcheck-endpoint-fails-if-low-disk-space
=> Use centralised status method

tests/app/main/test_briefs.py, tests/app/main/test_frameworks.py, tests/app/test_application.py
Ongoing work to refactor the tests for the FE apps (see https://github.com/alphagov/digitalmarketplace-briefs-frontend/pull/93 and https://github.com/alphagov/digitalmarketplace-user-frontend/pull/56).
Not too much to tidy in this app:
- Python 3 `super()` syntax
- Moving `data_api_client` patching to the class `setup` method (instead of using a decorator)
- Adding explicit `teardown` methods
=> Refactor test classes

config.py, tests/app/main/test_briefs.py
We sometimes send emails from 'do-not-reply@digitalmarketplace...'. If a
user does reply to this, they get directed to email enquiries. We should
just set our reply-to address as enquiries directly.
Guidance: https://www.gov.uk/service-manual/technology/how-to-email-your-users#allow-users-to-reply-to-you
=> Remove do-not-reply email address

app/main/helpers/briefs.py, app/main/views/briefs.py, app/templates/briefs/check_your_answers.html, app/templates/emails/brief_clarification_question_confirmation.html, requirements-app.txt, requirements.txt
`framework_framework` is an unnecessarily obtuse variable name and is
not overly descriptive of what it actually means. When used, this
describes the 'family' of framework being referenced. For example,
G-Cloud 10 is in the 'G-Cloud' family of frameworks. Digital Outcomes
and Specialists 2 is in the 'Digital Outcomes and Specialists' family.
Let's change all the references of `framework_framework` to
`framework_family`.
https://trello.com/c/iqFcVKpd/14
https://github.com/alphagov/digitalmarketplace-utils/pull/397
=> Rename framework_framework variable

app/assets/javascripts/application.js, app/assets/scss/application.scss, package.json, yarn.lock
**As a buyer I want to easily opt-in to user research so that I can help improve the buyer experience for G-Cloud**
The current opt-in journey has been unsuccessful, only 6 buyers have signed up. A higher number of suppliers, however, we suspect that this is due to G10 submission going on at the same time.
Buyer and suppliers cannot opt-in until they log in. Buyers and suppliers that don't log in don't have an opportunity to opt-in for user research.
***
**Changes**
Cookie banner to appear on all pages for logged in and logged out users until they click close or opt in. If clicked close, it reappears after 90 days.
***
**Notes**
Users will have to log in before they can opt-in.
We should use the existing opt-in journey as much as possible. This is non-mission work.
Ticket: …
=> Iterate opt in flow for user research participants

app/main/forms/briefs.py, app/main/views/briefs.py, app/templates/briefs/clarification_question.html
The validation link in the masthead was missing the `about
'brief.title'` bit after the masthead consolidation. This adds it back in.
=> Fix validation for brief clarification

app/main/views/frameworks.py, app/templates/frameworks/opportunities_dashboard.html, tests/app/main/test_frameworks.py
Trello: https://trello.com/c/WOrGaxBH/104-show-draft-applications-on-supplier-dashboard
Shows suppliers their draft applications in their dashboard, so they are less likely to mistakenly think their draft has already been submitted.
Old dashboard:
New dashboard:
Content and layout approved by @constancecerf. 
The functional tests pass locally.
A quirk in the application flow means that for now the 'Complete your application' link goes to the 'Check Your Answers' page only if the supplier has completed all the sections (but hasn't submitted). Otherwise we go to the start of the application journey for that brief (any saved answers will still show up). This is because the content loader manifest gets hugely confused if we jump to Check Your Answers early. This was a known issue when we …
=> Draft applications on supplier dashboard

requirements-app.txt, requirements.txt, tests/app/main/test_briefs.py, tests/app/test_application.py
This brings in `childSpanId` logging.
=> apiclient dependency: bump to v17.2.0

app/main/helpers/briefs.py, app/main/views/briefs.py, app/templates/briefs/check_your_answers.html, app/templates/briefs/clarification_question.html, app/templates/briefs/edit_brief_response_question.html, app/templates/briefs/question_and_answer_session.html, app/templates/briefs/start_brief_response.html, requirements-app.txt, requirements.txt
Trello: https://trello.com/c/PiwkC92B/476-brief-responses-templates-have-hardcoded-urls
Uses the external route for the public opportunity page (found on the Buyer FE app) rather than hardcoding.
Unfortunately we don't yet have an external route in `dmutils` for `/digital-outcomes-and-specialists/opportunities`.
Also pulls in the latest `utils.api_stubs` to make use of `framework.family` instead of `frameworkFramework`.
=> Use external route instead of hardcoded URLs

app/main/views/frameworks.py, app/templates/frameworks/opportunities_dashboard.html, tests/app/main/test_frameworks.py
Trello: https://trello.com/c/WOrGaxBH/104-show-draft-applications-on-supplier-dashboard
Ordering fail! The supplier should see the most urgent draft application at the top of the list.
I thought I'd done this ordering, and even wrote a test, but in fact I'd done the exact opposite 🤦‍♀️
=> Draft applications should be sorted with the earliest deadline first

requirements-app.txt, requirements.txt
Trello: https://trello.com/c/9HOV64oh/362-external-route-failure-for-frameworkfamily-opportunities-when-frameworkfamily-suppliers
The URL should now 404 instead of raising a 'NotImplementedError' (tested locally, all seems fine).
Also adds the Flask-FeatureFlags dependency (as per utils v40).
=> Pulls in latest utils to fix /suppliers/opportunities 500 error

app/main/__init__.py, package.json, yarn.lock
For [this trello ticket.](https://trello.com/c/VkAyVrzT)
See [this PR on the frameworks repo.](https://github.com/alphagov/digitalmarketplace-frameworks/pull/531)
DOS3 is coming and we need the manifests/questions etc.
=> Pull in latest frameworks for DOS3

app/templates/frameworks/opportunities_dashboard.html
Trello: https://trello.com/c/R3DsCXFa/22-use-frameworkfamily-frameworkfamily-in-apps-apiclient-rather-than-frameworkframework-frameworkframework
Only one usage of `framework.framework`, in a hardcoded URL. We can replace this with an external route, fix the quotes around the href value *and* switch to using `framework.family` in one nifty commit.
=> Use external URL with framework.family

app/__init__.py, app/main/errors.py, tests/app/test_application.py
Trello: https://trello.com/c/1K5ePclo/372-your-session-has-expired-instead-of-ugly-csrf-message
Redirects the user to the login page with an accompanying flash message. We can move this to utils in a separate PR.
**TLDR**: Flask is doing error handling weirdly, we can work around it by catching all 400s but only handling CSRFErrors. 
**Long version**:
I have a theory why Flask won't recognise the `CSRFError` in its own handler. The recommended advice from Flask-WTF (http://flask-wtf.readthedocs.io/en/stable/csrf.html) is to do something like this:
```
@application.error_handler(CSRFError):
def csrf_handler(e):
...
```
(We actually define our error handlers on the blueprint, not the application, however this is just a wrapper for the app functionality, and shouldn't make a difference.)
A …
=> Handle CSRFErrors as a subset of 400 errors

app/main/errors.py
Another error handling fix (see https://github.com/alphagov/digitalmarketplace-buyer-frontend/pull/828)
For this one, passing the `APIError` exception to `render_error_page` is actually correct, however I've changed it to just use the status code to be consistent with the other apps.
=> Brief Responses FE errors: pass status code to error handler as a kwarg

app/main/views/briefs.py, tests/app/main/test_briefs.py
Trello: https://trello.com/c/Virw5sGZ/114-500-error-question-not-found
If a supplier tries to submit a partially completed application, they are currently redirected to a generic 400 template, without any advice on how to fix the problem. 
There is no form to validate/grab formatted errors from, so we need to handle the possible error cases in a crude way, generating slightly less vague error messages:
- missing fields (400, the most likely occurrence)
- some other 400 (e.g. invalid date - should be picked up by form validation before this point)
- DB didn't update, so the status is still 'draft' (returned as a 200 OK)
- Something else (raise as a normal exception)
This seems like the quickest way to mitigate the problem for now - thoughts on better ways to do it welcome.
NB: I haven't …
=> Catch BadRequest responses from API when submitting applications

app/__init__.py, config.py, requirements-app.txt, requirements.txt
Trello https://trello.com/c/ZH9trgjH/419-snyk-alert-for-flask-010x-vulnerability
https://github.com/alphagov/digitalmarketplace-utils/pull/447
Again, little out of the ordinary here.
=> digitalmarketplace-utils dependency: bump to 43.0.0, remove any featureflags references

app/main/forms/briefs.py, app/templates/briefs/clarification_question.html, tests/app/main/test_briefs.py
This PR closes https://trello.com/c/dpQKpIn2/106-refactor-brief-responses-frontend-to-use-new-dmutilsforms-features
It requires https://github.com/alphagov/digitalmarketplace-utils/pull/444 and https://github.com/alphagov/digitalmarketplace-utils/pull/445
=> Update forms to use dmutils@42.x.x features

package.json, requirements-app.txt, requirements.txt, yarn.lock
Trello: https://trello.com/c/euSnpBnN/65-update-flask-login
- Update the Flask Login version
- Pull in related FE toolkit changes
No breaking changes to address for this app.
=> Brief Responses FE: Update Flask-Login to v0.4.1

app/main/views/briefs.py, tests/app/main/test_briefs.py
See https://trello.com/c/4OcRuemU
These are some delicate lines because they are the ones that govern what happens when people submit (or _think_ they submit) brief responses, so please check for any mistakes I may have made.
In this new behaviour, when we receive a submission `POST` request, note _first_ whether the brief is already closed (rather than waiting for an API failure and having to interpret its error message) - in which case give a clearer error message of "This opportunity has already closed for applications." (message ok'd by stefan) rather than the previous and rather open-ended generic "There was a problem submitting your application.". While we're at it, read 400 error messages from the API in a more foolproof way, so these don't get escalated to a 500 if the message is …
=>  brief response submission: make POST requests behave slightly more sanely when failing

package.json, yarn.lock
Trello: https://trello.com/c/c3mRFQNT/424-look-at-validation-on-briefresponsesdata-respondtoemailaddress
Pulls in Stefan's changes to the hint text on the Brief Response reply-to email address form.
The other major bumps to the frameworks repo do not affect the Brief Responses FE (search and draft v7 schemas).
=> Pull in hint text for Reply-To email address

package.json, tests/app/test_application.py, yarn.lock
https://trello.com/c/3om47rfx/601-update-remaining-instances-of-enquiriesdigitalmarketplaceservicegovuk-to-the-new-support-address
Most of the 404 error pages fall through to the Buyer FE, which is showing the new support email address. But duff URLs served by the other FE apps (e.g. `/suppliers/opportunities/i-have-typed-this-url-badly`) haven't yet had the FE toolkit bumped.
The breaking change is for the reverted attempt to fix the JS for the functional tests.
=> FE toolkit error pages

config.py, default.nix
https://trello.com/c/HsZ9mj7o
This should only ever show itself in place of a CSRF token failure, so should be a fairly safe thing to enable.
=> set DM_COOKIE_PROBE_COOKIE_EXPECT_PRESENT, enabling cookie error page

gulpfile.js, package-lock.json, package.json
Introduces Standard JS for linting but only checks gulpfile.js. If you run npx standard you will see all the other files that fail Standards rules. We have decided not to address all the other javascript files at this point as we feel it would be better to look at them when we come to updating the javascript and using GOV.UK Frontend.
Trello Card: https://trello.com/c/ZkJAWEnM
=> Add Standard JS

app/templates/_base_page.html, app/templates/briefs/_base_edit_question_page.html, app/templates/briefs/application_submitted.html, app/templates/briefs/check_your_answers.html, app/templates/briefs/clarification_question.html, app/templates/briefs/not_is_supplier_eligible_for_brief_error.html, app/templates/briefs/question_and_answer_session.html, app/templates/briefs/start_brief_response.html, app/templates/frameworks/opportunities_dashboard.html
https://trello.com/c/PpFz5qRc/43-create-a-base-page-for-the-apps
The work to move to govuk-frontend will be easier if we have a base page in each app in which to import macros.
GOVUK Frontend may solve this down the road
https://github.com/alphagov/govuk-frontend/issues/1278
It seems from research (Googling and GOV Pay) for now this is the accepted pattern
=> 43-create-a-base-page-for-the-apps

app/assets/scss/application.scss, app/assets/scss/overrides/_page_headings.scss, app/templates/briefs/_base_edit_question_page.html, app/templates/briefs/application_submitted.html, app/templates/briefs/check_your_answers.html, app/templates/briefs/clarification_question.html, app/templates/briefs/question_and_answer_session.html, app/templates/briefs/start_brief_response.html, app/templates/frameworks/opportunities_dashboard.html, tests/app/main/test_briefs.py
Update all headings to use HTML tags with GOV.UK Frontend heading styles instead of the digitalmarkteplace-frontend-toolkit page-heading template
=> 24-2-update-page-headings-to-govuk-frontend-style-in-brief-responses-frontend

requirements-app.txt, requirements.txt
https://trello.com/c/51brdJKx/1201-upgrade-pyyaml-to-5x
Bumps the content-loader (and its PyYAML dependency) to bring in the security fix. Functional tests pass locally 👍
=> Bump contentloader and PyYaml

app/assets/scss/application.scss, app/templates/_base_page.html, app/templates/briefs/application_submitted.html, app/templates/briefs/check_your_answers.html, app/templates/briefs/clarification_question.html, app/templates/briefs/edit_brief_response_question.html, app/templates/briefs/question_and_answer_session.html, app/templates/briefs/start_brief_response.html, app/templates/frameworks/opportunities_dashboard.html, tests/app/helpers.py, tests/app/main/test_briefs.py
Use GOV.UK frontend breadcrumbs element
https://trello.com/c/WfVAHKfa/22-2-update-breadcrumbs-to-use-govuk-frontend-component-in-brief-responses-frontend
* Add element macro import to _base_page.html
* Remove GOV.UK toolkit breadcrumb from application.scss
* Override content block to add a beforeContent block in _base_page.html
* Change breadcrumbs to use macro
=> 22-2-update-breadcrumbs-to-use-govuk-frontend-component-in-brief-responses-frontend

app/assets/scss/application.scss, app/assets/scss/overrides/_notification-banner.scss
There is a current issue with vertical spacing of notifications. This
commit adds it temporarily but idealy the component itself should be
adding the margin spacing it requires.
=> Adding vertical spacing to notifications

app/assets/javascripts/application.js
This was missed when adding digitalmarketplace-govuk-frontend, we should add it now.
=> Add JavaScript init for GOV.UK Frontend JavaScripts

app/templates/_base_page.html, app/templates/briefs/_base_edit_question_page.html, app/templates/briefs/application_submitted.html, app/templates/briefs/check_your_answers.html, app/templates/briefs/clarification_question.html, app/templates/briefs/not_is_supplier_eligible_for_brief_error.html, app/templates/briefs/question_and_answer_session.html, app/templates/briefs/start_brief_response.html, app/templates/frameworks/opportunities_dashboard.html, config.py, package-lock.json, package.json, tests/app/test_application.py
Ticket: https://trello.com/c/ZxYMd5ET/95-use-error-page-templates-from-digital-marketplace-govuk-frontend
This PR updates digitalmarketplace-govuk-frontend to v0.2.1 and adds its templates to the Jinja environment, which has the effect of changing its error pages to use newer styles.
---
=> Use Digital Marketplace GOV.UK Template error pages

app/templates/briefs/application_submitted.html, app/templates/briefs/check_your_answers.html, app/templates/briefs/clarification_question.html, app/templates/briefs/edit_brief_response_question.html, app/templates/briefs/question_and_answer_session.html, app/templates/briefs/start_brief_response.html, requirements-app.txt, requirements.txt
Ticket: https://trello.com/c/hubmy1jb/1108-remove-the-escape-filter-from-br-fes-templates-because-autoescaping-is-turned-on
govuk-frontend-jinja > v0.5.0 enables autoescaping on Nunjucks templates by
default, so we don't need to escape inputs to macros.
=> Remove manual escaping from Jinja templates

app/assets/scss/application.scss, app/templates/briefs/application_submitted.html, app/templates/briefs/check_your_answers.html, tests/app/main/test_briefs.py
We don't need to use a template or custom CSS to insert a link.
This PR also changes the copy of the link to be clearer; thanks @aliuk2012 for the suggestion.
=> Remove secondary-action-link component

.travis.yml, requirements-app.txt, requirements-dev.txt, requirements.txt
https://trello.com/c/GsDBHBo7/135-switch-on-python-37-and-38-travis-checks-to-check-potential-dependency-problems-before-upgrade
- Bumps content loader, utils, test utils and API client
- Adds 3.7 and 3.8 to Travis config
=> Add Python 3.7 and 3.8 checks to Travis

app/assets/javascripts/application.js, tests/app/test_application.py
https://trello.com/c/Eth9oZbJ/203-disable-ga-cookies-temporarily
Temporarily switching off GA functionality while we review our cookie policy.
See equivalent Buyer FE PR: alphagov/digitalmarketplace-buyer-frontend#970
=> Exclude analytics code from application.js

app/templates/briefs/check_your_answers.html
When we migrated over to govuk-frontend and updating the grid we accidentally
used the wrong class name for a 100% width row. This meant that the tables overflowed outside the main page wrapper.
=> Fix layout overflow because wrong class was being used

app/assets/javascripts/application.js, app/templates/_base_page.html, package-lock.json, package.json, requirements-app.txt, requirements.txt, tests/app/test_application.py
https://trello.com/c/hGlNERQ6/294-3-cookie-settings-page-incl-analytics-roll-out
Introduces the new opt-in cookie banner.
See equivalent for Buyer FE alphagov/digitalmarketplace-buyer-frontend#986
- pulls in CookieBanner component from DM GOVUK Frontend
- pulls in utils fix for the new external /user/cookie-settings route
- adds banner to base page template
- reinstates a cookie banner unit test (removing a redundant test checking for old analytics JS)
=> Update cookie banner

app/templates/briefs/check_your_answers.html, tests/app/main/test_briefs.py
Ticket: https://trello.com/c/zzrRBDzm/1365-page-title-on-brief-response-check-your-answers-page-doesnt-match-content
The page title should be the same as the page heading, and different from the page title for other pages
=> Fix page title for check your answers page

.gitignore, .secrets.baseline, app/assets/javascripts/application.js, app/assets/scss/application.scss, config.py, gulpfile.js, package-lock.json, package.json
https://trello.com/c/fhL8Zl8T/175-3-unbundle-govuk-frontend-from-digitalmarketplace-govuk-frontend
digitalmarketplace-govuk-frontend has been updated so that it is no longer bundled with govuk-frontend.
This PR addresses those changes.
=> Install digitalmarketplace-govuk-frontend and govuk-frontend separately

app/main/forms/briefs.py, app/main/views/briefs.py, app/templates/_base_page.html, app/templates/briefs/_base_edit_question_page.html, app/templates/briefs/clarification_question.html, package-lock.json, package.json, requirements.in, requirements.txt, tests/app/main/test_briefs.py
https://trello.com/c/x5aacZhG/282-1-replace-validation-banner-with-govuk-frontend-error-summary-component-in-the-brief-responses-frontend
It was a bit tricky to know where to bound this ticket, as there were a few issues with `boolean` type questions (https://github.com/alphagov/digitalmarketplace-content-loader/pull/119) and with the focus of Error Summary links.
Since the content loader ticket (https://trello.com/c/13tOvxuu/285-2-replace-content-loader-form-macros-in-brief-responses-frontend) should take care of the focus issues for most questions, my strategy is to keep this a separate concern and not fix the focus issues (specifically, that clicking on a link in the Error Summary can pull focus to the question but not show the question title, since it's been separately set as the page …
=> Replace validation banners

app/main/views/briefs.py, app/templates/_base_page.html, tests/app/main/test_briefs.py
Ticket: https://trello.com/c/n4xGRS3w/283-1-replace-flash-messages-with-digital-marketplace-govuk-frontend-alert-component-in-brief-responses-frontend
We want to use the dmAlerts macro instead of the old flash-messages template, as dmAlert is based on GOV.UK Design System styles and guidance.
=> Replace flash messages with alerts

package-lock.json, package.json
- [Changelog](https://github.com/alphagov/digitalmarketplace-govuk-frontend/blob/master/CHANGELOG.md)
=> Bump digitalmarketplace-govuk-frontend from 2.1.0 to 2.9.0

app/__init__.py, app/assets/scss/application.scss, app/assets/scss/overrides/_pricing-input.scss, app/templates/briefs/_base_edit_question_page.html, app/templates/briefs/start_brief_response.html, app/templates/macros/show_question.html, package-lock.json, package.json, requirements.in, requirements.txt, tests/app/main/test_briefs.py
https://trello.com/c/13tOvxuu/285-2-replace-content-loader-form-macros-in-brief-responses-frontend
Two cases are not simply dealt with, and I've popped them into a conditional branch on the template.
1. Pricing inputs require a prefix, which is not available in govuk-frontend v2, but is available in v3
2. `niceToHaveRequirements` relies on conditional content, so we want to rework the journey to avoid this.
This makes use of some markdown tweaks in the Frameworks repo: https://github.com/alphagov/digitalmarketplace-frameworks/pull/658
=> Replace content loader macros

app/main/views/frameworks.py, app/templates/_base_page.html, app/templates/frameworks/opportunities_dashboard.html, requirements.in, requirements.txt, tests/app/main/test_frameworks.py
https://trello.com/c/jgoHhWX3/284-3-replace-summary-table-in-opportunities-dashboard-in-brief-responses-frontend
Swapping out Frontend Toolkit summary table for Design System `govukTable`.
=> Replace summary table on opportunities dashboard

app/assets/scss/application.scss, app/assets/scss/overrides/_hint.scss, app/main/forms/briefs.py, app/templates/_base_page.html, app/templates/briefs/clarification_question.html, tests/app/main/test_briefs.py
https://trello.com/c/jQkYTPiU/296-1-replace-text-input-and-textarea-components-in-respond-to-a-dos-opportunity-journey
=> Use govukCharacterCount instead of Frontend Toolkit Textbox

app/assets/scss/application.scss, app/assets/scss/overrides/_dm-table.scss, app/assets/scss/overrides/_summary-list.scss, app/templates/_base_page.html, app/templates/briefs/_brief_response_data.html, requirements.in, requirements.txt, tests/app/main/test_briefs.py
https://trello.com/c/2oltxnyO/299-3-replace-summary-table-on-check-your-answers-in-brief-responses-frontend
I investigated moving the logic for this into the controller, but that resulted in a raft of helper functions drowning in loops and branches.
So instead, I'm using Jinja's namespace to create the rows object within the template and pass it to the GOVUK Frontend components.
I haven't handled the `boolean_list` case because this only applies to DOS1, for which this page doesn't appear to be accessible anymore (since the dashboard only shows the live Framework plus the previous one). See https://github.com/alphagov/digitalmarketplace-frameworks/search?q=boolean_list
Because of these changes, we need some tweaks to the functional tests: …
=> Replace summary table for Check Your Answers

app/main/__init__.py, package-lock.json, package.json
This is needed for making DOS 5 live. I don't know how/why we missed doing it earlier. Should un-break Preview.
Following the example from DOS 4: https://github.com/alphagov/digitalmarketplace-brief-responses-frontend/pull/127
=> Load DOS 5 content 

requirements.in, requirements.txt
This picks up changes in https://github.com/alphagov/digitalmarketplace-content-loader/pull/124
which prevented users from being able to submit a brief response.
=> Bump content loader patch version

app/templates/briefs/application_submitted.html, app/templates/briefs/clarification_question.html, app/templates/briefs/question_and_answer_session.html
https://trello.com/c/LdwIhKyT/295-2-remove-old-styles-and-dmspeak-from-brief-responses-frontend
`check_your_answers` and `base_edit_question_page` will be covered in separate PRs (`check_your_answers`: #255), so I've only removed these styles from other templates.
=> Remove frontend toolkit typography styles

package-lock.json, package.json
Pick up the updated example content added in https://github.com/alphagov/digitalmarketplace-frameworks/pull/666
https://trello.com/c/bQUiYaju/702-update-date-examples-to-2021
=> Bump digitalmarketplace-frameworks version

app/templates/briefs/_base_edit_question_page.html, requirements.txt
digitalmarketplace-content-loader>=7.29.0 supports multiquestions, we can get rid of (some of) the special logic in `_base_edit_question_page.html`.
=> Use render_question() to get HTML for multiquestion forms

app/templates/briefs/_base_edit_question_page.html, requirements.txt, tests/app/main/test_briefs.py
Ticket: https://trello.com/c/cMtAeSL2/764-3-add-support-for-conditionally-revealed-content-to-dmcontentgovukfronted
Depends on https://github.com/alphagov/digitalmarketplace-content-loader/pull/132
digitalmarketplace-content-loader>=7.30.0 supports followup questions in multiquestions, so we can use it to display the `niceToHaveRequirements` question.
=> Use render_question() for niceToHaveRequirements

.github/workflows/test.yml
Since `lxml` upgrade in #259  we no longer need additional ubuntu dependencies to build against python 3.9.
=> remove unneeded ubuntu dependencies

.nvmrc
https://trello.com/c/0BmkYFSD/907-3-node-10-is-eol-april-2021-upgrade-node-to-v14  
Run Node 14 LTS locally first before trying it on docker/PaaS.
=> use node 14 LTS

app/main/views/briefs.py, tests/app/main/test_briefs.py
https://trello.com/c/FGm8bi13/3-2-suppliers-may-be-missing-out-on-opportunities-due-to-misleading-banner
We believe that this success flash message is misleading some suppliers. We have some evidence to suggest that they think the flash message means that they've successfully submitted their brief response. This means that they don't press the button to submit their application.
Our evidence here is not definitive - we've got a pattern of support requests, but we've not done any user research or proper analysis.
We don't need this flash, however. Users can see on the page that their information has been updated.
For this reason, we're just going to go ahead and remove the flash. We'll check back in a few weeks to see what effect it's had on the rate of submitted brief responses and …
=> Remove success flash when updating brief response
