Crown-Commercial-Service/digitalmarketplace-brief-responses-frontend

- Dockerfile
It includes an update to the nginx config for the nginx running next to
the app. Without it status checks to a status endpoing with three or
more forward slashes in the url path will fail.
> Pull in version 2.0.4 of docker base file

- default.nix
'nuff said. This ain't the supplier frontend anymore.
> default.nix: set shortName appropriately for this app

- app/__init__.py
Fixes warnings introduced by the latest dependency bumps:
`CsrfProtect` -> `CSRFProtect`
`@csrf.error_handler` -> `@application.errorhandler(CSRFError)`
> Fix dependency warnings

- app/main/views/briefs.py
- tests/app/main/test_briefs.py
Trello: https://trello.com/c/y4bHoTGs/333-investigating-potential-issue-leading-suppliers-to-believe-their-brief-responses-are-submitted-when-they-arent
Fixes a bug whereby failed API submit requests were not handled correctly. Previously the supplier was redirected to the success page and shown a success flash message, even though their application was not submitted (for example, due to an API app crash).
The supplier now remains on the Check Your Answers page and sees an error message if the response either contains an `error` or the status is still `draft`.
Also, if a supplier reaches the `/result` stage when their application is still at the `draft` stage, they are redirected back to the Check Your Answers page.
We have good functional test coverage for the happy path here but not for …
> Application submit failure should not redirect to success page

- app/main/helpers/briefs.py
- requirements-app.txt
- requirements.txt
- tests/app/main/test_briefs.py
Upgrade to flask 1.0.2
http://flask.pocoo.org/docs/1.0/changelog/#version-1-0-2
https://trello.com/c/bBDir2Gp/18-flask-1x-upgrade
> Upgrade to flask 1.0.2

- app/__init__.py
- requirements-app.txt
- requirements.txt
- tests/app/main/test_metrics.py
https://trello.com/c/IOBExody/295-add-custom-python-metrics-to-supplier-frontend
https://github.com/alphagov/gds_metrics_python/tree/master/gds_metrics
> Add metrics to brief-responses frontend and test

- app/__init__.py
- app/metrics/__init__.py
- tests/app/main/test_metrics.py
* Add new metrics blueprint
* Register against app with prefix
* Subclass GDSMetrics
* Prevent registration of metrics url against base app object
* Register metrics url against new metrics blueprint
> Use metrics as blueprint

- Dockerfile
Update with new docker base image 4.1.0 for new nginx conf
> 322-move-metrics-to-metrics-and-expose

- app/main/__init__.py
- package.json
- yarn.lock
https://trello.com/c/OD16c4bI/552-pull-in-dos-content-to-briefs
Pull in the DOS4 content and load the manifests.
> Load DOS4 content

- app/main/__init__.py
- requirements-app.txt
- requirements.txt
This makes the `content_loader` threadsafe using an identical approach to https://github.com/alphagov/digitalmarketplace-supplier-frontend/pull/1078
Also bumping versions of dependencies to support this.
> threadsafety

- app/main/views/frameworks.py
- requirements-app.txt
- requirements.txt
- tests/app/main/test_frameworks.py
https://trello.com/c/2FBIg5LP
Again having trouble with pip & werkzeug, will create a ticket about it.
> opportunities_dashboard view: use with_data=False for find_brief_responses() call

- app/__init__.py
- app/assets/javascripts/application.js
- app/assets/scss/application.scss
- config.py
- gulpfile.js
- package-lock.json
- package.json
- requirements-app.txt
- requirements.txt
Following steps on ticket:
https://trello.com/c/ZtEH5XcG/20-2-add-govuk-frontend-jinja-and-digitalmarketplace-govuk-frontend-to-brief-responses-frontend
> Add govuk-frontend-jinja and digitalmarketplace-govuk-frontend

- app/assets/scss/application.scss
- app/templates/_base_page.html
- app/templates/briefs/check_your_answers.html
- app/templates/briefs/clarification_question.html
- app/templates/briefs/edit_brief_response_question.html
- app/templates/briefs/start_brief_response.html
- tests/app/main/test_briefs.py
trello: https://trello.com/c/N1CO6kFY/32-2-update-buttons-to-use-govuk-frontend-component-in-brief-responses-frontend
> 32-2-update-buttons-to-use-govuk-frontend-component-in-brief-responses-frontend

- app/assets/scss/application.scss
- app/templates/briefs/_base_edit_question_page.html
- app/templates/briefs/application_submitted.html
- app/templates/briefs/check_your_answers.html
- app/templates/briefs/clarification_question.html
- app/templates/briefs/not_is_supplier_eligible_for_brief_error.html
- app/templates/briefs/question_and_answer_session.html
- app/templates/briefs/start_brief_response.html
- app/templates/frameworks/opportunities_dashboard.html
- spec/javascripts/unit/AnalyticsSpec.js
trello: https://trello.com/c/OEdt148E/30-3-update-grids-to-use-govuk-frontend-styles-in-brief-responses-frontend
> grid changes

- app/main/forms/briefs.py
- app/templates/briefs/_brief_response_data.html
- app/templates/briefs/application_submitted.html
- app/templates/briefs/check_your_answers.html
- app/templates/briefs/clarification_question.html
- app/templates/briefs/edit_brief_response_question.html
- app/templates/briefs/not_is_supplier_eligible_for_brief_error.html
- app/templates/briefs/question_and_answer_session.html
- app/templates/briefs/start_brief_response.html
- app/templates/frameworks/opportunities_dashboard.html
trello: https://trello.com/c/RzRAhmef/33-3-use-govuk-link-govuk-list-and-govuk-body-styles-in-brief-responses-frontend
> govuk classes for anchor, list and paragraph elements

- app/assets/javascripts/application.js
> Fix JavaScript; Add missing semicolon

- app/templates/briefs/application_submitted.html
- app/templates/briefs/start_brief_response.html
> Remove lead paragraphs

- gulpfile.js
These will be needed for https://trello.com/c/5RIlSNJ9/
> Add GOV.UK Frontend image assets to app

- Makefile
- requirements-dev.in
- requirements-dev.txt
- requirements.in
- requirements.txt
https://trello.com/c/2GcrMr2g/401-ensure-all-repos-have-pip-and-pip-tools-setup-similarly
> Fix inconsistencies in Makefile

- app/assets/javascripts/application.js
- app/assets/scss/application.scss
- app/templates/_base_page.html
- config.py
- package-lock.json
- package.json
Bumps digitalmarketplace-govuk-frontend and govuk-frontend-jinja.
> Update Digital Marketplace frontend libraries

- Procfile
- application.py
- requirements.in
- requirements.txt
https://trello.com/c/kbhJdTm3/567-remove-flaskscript-from-dmutils
> Remove Flask-Script

- app/main/views/frameworks.py
- app/templates/_base_page.html
- app/templates/frameworks/opportunities_dashboard.html
- requirements.in
- requirements.txt
- tests/app/main/test_frameworks.py
Reverts alphagov/digitalmarketplace-brief-responses-frontend#248
This is causing functional test errors on staging.
Also reverting https://github.com/alphagov/digitalmarketplace-functional-tests/pull/826
> Revert "Replace summary table on opportunities dashboard"

- app/main/views/frameworks.py
- app/templates/_base_page.html
- app/templates/frameworks/opportunities_dashboard.html
- requirements.in
- requirements.txt
- tests/app/main/test_frameworks.py
Reverts alphagov/digitalmarketplace-brief-responses-frontend#249
Functional tests should now be... functional. https://github.com/alphagov/digitalmarketplace-functional-tests/pull/831
> Revert "Revert "Replace summary table on opportunities dashboard""
